### ISSUE TITLE
Separate Observable from Subjects

### ISSUE THREAD

**Issue by minamorl** [minamorl/rex#7]
I am currently thinking about proper design for it. Before working of them I need to sort out the design.

**Comment by PhilippMDoerner** [comment]
I'm tinkering on something, but that is more a full-blown reimplementation than just a small design change that shares the fundamental idea. If you want to take a look at the WIP see here: 

https://github.com/PhilippMDoerner/rex/tree/reimplement

(For reference if you take a look at this, I was initially playing around with having everything in the same file before I decided to split it apart. I didn't commit the first approach so I kept it in the branch for now in the file funcbackup.nim which I'll likely end up deleting in the future).

This solves several things at once:
- Splits out subjects from Observables
- Splits out operator functions into their own modules which should make extending easier and undesired coupling harder
- Moves "reactive" types such as Subjects out into their own modules which should be beneficial for the same reasons
- Everything under the hood solely relies on Observables/converts to Obervables, which should reduce coupling as much as possible
- You get lazy-loading of data into your observables now. By which I mean, using map/filter etc. does **not** trigger any computation *until* somebody subscribes. And no data gets copied along the way, so observables derived from other observables don't copy their data (in a transformed way or the like), meaning you get a lot less data duplication
- You can now react to "completion" of the observable/subject as well as error cases that might occur in an observable or any of the operators along the way (or rather, the error thing will be possible once I finished the implementation, testing etc.)

This *is* a bit much at once I'll admit, I'd offer it as a PR if you want, given that this project provided the first draft and starting inspiration. 
If not I'd likely spin it out into another library as this approach with closures and inheritance from an Observable type seems like it'd be flexible enough to implement the entire reactiveX spec and overcome limitations that I previously struggled with.

**Comment by minamorl** [comment]
Hi @PhilippMDoerner. I checked your repo.
It's entirely better than my first implementation i think. You can be a maintainer of this library If you want to. I think it's better to have a great library in one place rather than having people develop it separately, so if you'd like, I'd like to make you a maintainer.

**Comment by minamorl** [comment]
On a personal note, I am currently very busy looking for a job and do not seem to have the ability to continue developing this library full time at this time. However, I think I can check the direction of the project.

**Comment by PhilippMDoerner** [comment]
All good. I'm making semi-slow progress on my end. A couple of problems were complex enough that they made me kind of hit a wall that I managed to get through for now.

The following have been added for now:
- error handling, error callback functions now get called if any exceptions occur
- Observables can now be defined using a callback function like you did initially. So they can now emit multiple values according to arbitrarily complex logic
- unsubscribing is a thing now

All of the above is tested as well.

What I'm still working on before the PR (so that we get feature parity and because I deem these an important subset of functionality to "test" if my current approach is flawed or not):
- combineLatest
- throttle
- tap - particularly I need to think about if I need to take care of the observer it establishes

**Comment by PhilippMDoerner** [comment]
I've hit a snag with combineLatest which unveiled a weakness in the current design.
I **wanted** so badly to share some code between some of the observable types, such as `subscribe`, `complete` etc. because it felt immensely repetitive. So I defined them as global procs in general instead of procs stored in fields on their various observables.

It turns out that really is a bad idea because it leads to bugs when it comes to e.g. "combined" observables.
The latest in the saga being that with current behavior a combined-observable automatically completes when any of its parents is a cold observable because the current logic applies that if a parent of an observable is complete, its child must also be complete - which holds up, but not for combined observables which may have a hot observable as a parent that is not yet complete.

Therefore I'll need to do yet another refactor on the approach.
Instead of sharing some procs like `subscribe` and `complete` I'll need to make these fields on `Observable` that I attach the procs to. Its sort of a poor man's OOP because we can't have generic methods.

This means the type of Observable must change from
```nim
type
  Observable*[T] = ref object of RootObj
    observers: seq[Observer[T]]
    initialHandler: proc(observer: Observer[T])
    hasInitialValues: bool # Indicates whether the observable has values that must be emitted immediately when somebody subscribes to it. If this is true, initialHandler *must* not be nil. This is true for cold observables, ReplaySubjects, BehaviorSubjects and similar
    completed: bool
```
to
```nim
type 
  Observable*[T] = ref object of RootObj
    observers: seq[Observer[T]]
    subscribe: proc(observer: Observer[T])
    unsubscribe: proc(observer: Observer[T])
    complete: proc()
    completed: bool
```

Based upon which I can then inherit with types like `Subject`, `CombinedObservable2`, `CombinedObservable3` etc.

This will take some time and effort, but in exchange it *should* be much less bug-prone.
